### ISSUE TITLE
第一秒的邻发射数计算不正确

### ISSUE THREAD

**Issue by Tanimodori** [CHanzyLazer/GT6_nuclear_simulator#2]
例如将一个`Pu239`与`Abs`相邻放置于工业冷却液的2x2反应堆中，此时`Pu239`的自发射数和邻发射数均为`512`，但是在第一秒时`Abs`接收到的中子数却是`427`：

![image](https://github.com/CHanzyLazer/GT6_nuclear_simulator/assets/29478770/83371b6d-d7a9-4b5b-afd9-4ef456cc6d6c)

原因是在每步模拟函数`next_20tick`中调用的燃料棒的邻发射数计算函数`cal_emissiom_num`错误：

https://github.com/CHanzyLazer/GT6_nuclear_simulator/blob/1cd254810c30a2e40a1fce675d33ebc6465f95db/main.py#L1430-L1435

这里的计算公式为`e + ((n-s[k])*f)`，取自Erik写的官方文档`gt6fission.pdf`，此处的`n-s`项，虽然直接的意思是“上一秒接收到的中子减去自发射数”，其实际含义应该是“上一秒接收到其他燃料棒发射的中子数”，其数量不应该为负数，这一点可以参考GT6源代码

https://github.com/GregTech6/gregtech6/blob/32e81b3f5b5e62fca45d6163ba1bfc514237d60e/src/main/java/gregtech/tileentity/energy/reactors/MultiTileEntityReactorRodNuclear.java#L175-L200

```java
long tEmission = tNeutronOther + UT.Code.divup(Math.max(aReactor.oNeutronCounts[aSlot]-tNeutronSelf, 0), tNeutronDiv);
```

此处将`n-s`取非负值，而模拟器中将整个计算结果`e + ((n-s[k])*f)`取了非负值，而`n-s`为负值之一的常见情况为第一秒时，此时`n=0`、`s>0`，故造成邻发射数小于燃料棒类型标称的邻发射数的模拟错误。

**Comment by liqa1024** [comment]
好，这个错误的原因是gt6的早期版本中确实会出现负值，当时是一致的，后面更新greg加上了绝对值

**Comment by Tanimodori** [comment]
> 好，这个错误的原因是gt6的早期版本中确实会出现负值，当时是一致的，后面更新greg加上了绝对值

确实，见 https://github.com/GregTech6/gregtech6/commit/18030ea4ace7906a12ea7caa1fa50276d8fbc93f
