### ISSUE TITLE
增殖棒的loss计算错误

### ISSUE THREAD

**Issue by sentend9** [CHanzyLazer/GT6_nuclear_simulator#4]
游戏里,增殖棒应该是每次累加后扣除一次
但是模拟器里,每次增加的时候就扣除一次,举例:假设一根增殖棒的loss值是1000,边上4个燃料棒,每轮发出2000到增殖棒,理论上应该是2000*4-1000=7000,而模拟器是(2000-1000)*4=4000
--------是我没理解对,原程序没有问题---------

另外提一些小问题,
1.因为游戏更新,新增了燃料棒,当我去改配置打算新增时,会报错,因为主程序把燃料棒每个类型的数量固定了,来自main.py第157行         col_nums = [3, 5, 5, 3, 3, 3]
2.熔融钍盐描述中的1[0000HU]应改为2[560000HU]
3.所有的描述[这个燃料棒十分重要]应改为[这个燃料棒非常危险]或者[这个燃料棒非常致命]

**Comment by sentend9** [comment]
失误

**Comment by liqa1024** [comment]
- 新版更新的东西其实已经有人做了跟进，并且我也合并到了源码里，只是没有打包成 exe，如果需要可以自行打包或者直接运行：
  
  ```shell
  python main.py
  ```
  
  注意需要有 python 环境并且有这些依赖：
  
  ```shell
  pip install pillow
  pip install mouse==0.7.0
  pip install pyyaml
  pip install ruamel.yaml
  ```

- 现在可以通过 data.yml 修改 col_nums 了（虽然也已经包含了更新的燃料棒）

- *这个燃料棒十分重要* 确实是翻译错误，这里改为了 *这个燃料棒是临界的*
